Repository thecorecity/cognitum, pull requests merged in 2020-06, with the labels that each got.

#5 Try to fix English translation, add Russian, Ukrainian, and 🇸🇰 SLOVAK 🇸🇰 variants
  README.md
  lang/en.json
  lang/ru.json
  lang/sk.json
  lang/ua.json
Labels: enhancement

#6 Lang class get instance method fallback to English
  lib/classes/Lang.js
  lib/classes/LanguagePack.js
Labels: enhancement

#11 Fix command not resolving on calling HelpCommand
  lib/commands/basic/HelpCommand.js
Labels: bug

#12 Minor JSDoc improvements
  .editorconfig
  lib/classes/CommandsRegistry.js
  lib/classes/Config.js
  lib/classes/Lang.js
  lib/classes/MessageParser.js
Labels: documentation, enhancement
